// flow-typed signature: a0b6821239f43db04a19e803c1d79cb3
// flow-typed version: <<STUB>>/http_v0.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
