// flow-typed signature: 53b2959452e4b441b15273339f181f45
// flow-typed version: <<STUB>>/node-rdp_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rdp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rdp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rdp/lib/rdp-cli' {
  declare module.exports: any;
}

declare module 'node-rdp/lib/rdp-connect' {
  declare module.exports: any;
}

declare module 'node-rdp/lib/rdp-file' {
  declare module.exports: any;
}

declare module 'node-rdp/lib/rdp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rdp/lib/rdp-cli.js' {
  declare module.exports: $Exports<'node-rdp/lib/rdp-cli'>;
}
declare module 'node-rdp/lib/rdp-connect.js' {
  declare module.exports: $Exports<'node-rdp/lib/rdp-connect'>;
}
declare module 'node-rdp/lib/rdp-file.js' {
  declare module.exports: $Exports<'node-rdp/lib/rdp-file'>;
}
declare module 'node-rdp/lib/rdp.js' {
  declare module.exports: $Exports<'node-rdp/lib/rdp'>;
}
