// flow-typed signature: 903323e1c841310f0ab170b8c82050bc
// flow-typed version: <<STUB>>/ssh-exec_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssh-exec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssh-exec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ssh-exec/index' {
  declare module.exports: $Exports<'ssh-exec'>;
}
declare module 'ssh-exec/index.js' {
  declare module.exports: $Exports<'ssh-exec'>;
}
