// flow-typed signature: f197f46cb1f156f4c6c4232eae893ce2
// flow-typed version: <<STUB>>/symple_v*/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'symple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'symple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'symple/lib/adapter' {
  declare module.exports: any;
}

declare module 'symple/lib/peer' {
  declare module.exports: any;
}

declare module 'symple/lib/symple' {
  declare module.exports: any;
}

declare module 'symple/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'symple/lib/adapter.js' {
  declare module.exports: $Exports<'symple/lib/adapter'>;
}
declare module 'symple/lib/peer.js' {
  declare module.exports: $Exports<'symple/lib/peer'>;
}
declare module 'symple/lib/symple.js' {
  declare module.exports: $Exports<'symple/lib/symple'>;
}
declare module 'symple/server.js' {
  declare module.exports: $Exports<'symple/server'>;
}
